-- Retrieve all the rows and columns
SELECT * FROM ORDERS;

--Retrieve order id and CUSTOMER ID PURCHASED THE ORDER
SELECT ORDER_ID, CUSTOMER_ID
FROM ORDERS;

--Retrieve data of orders who purchased ON 23/3/2026
SELECT * FROM ORDERS
WHERE ORDER_DATE='23/3/2026';

--Retrieve CUSTOMER ID AND NO OF THE PURCHASES THEY MADE
SELECT CUSTOMER_ID, COUNT(*) AS NO_OF_PURCHASES
FROM ORDERS
GROUP BY CUSTOMER_ID;

--Retrieve customer ID AND PRICE OF THEIR PURCHASE
SELECT S.CUSTOMER_ID, C.PRICE
FROM ORDERS S INNER JOIN ORDER_DETAILS C
ON S.ORDER_ID=C.ORDER_ID;

--Retrieve order date  and no of sales on that day if sales are more than 2
SELECT ORDER_DATE,count(*) as Total_sales
GROUP BY ORDER_DATE HAVING COUNT(*)>2;